version: "3"
services: 
  node:
      build: .
      image: fake-device
      ports:
        - 3338:3338
      container_name: fake-device-api
  nginx:
      image: nginx:alpine
      ports:
        - 8008:80
      volumes:
        - ./web_ui:/usr/share/nginx/html
        - ./d_volumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      container_name: fake-device-webui

